# MQ 类型选择
#mq-type: rabbitmq
#mq-type: rocketmq
#mq-type: redis
mq-type: none

#rocketmq:
rocketmq:
  name-server: localhost:9876 # 访问地址
  producer:
    group: Pro_Group # 必须指定group
    send-message-timeout: 10000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2

spring:
  #  cache:
  #    type: none 即可关闭缓存功能
  data:
    redis:
      port: 6379
      host: localhost
      password: 123456
      database: 0
      timeout: 5s
      lettuce:
        pool:
          max-active: 20
          max-idle: 30
          min-idle: 5
          max-wait: 10s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/deliver?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: deliver
    publisher-confirm-type: correlated
  quartz:
    job-store-type: memory # 使用内存存储任务（默认）
    properties:
      org:
        quartz:
          scheduler:
            instanceName: InMemoryScheduler # Quartz调度器实例名称，用于区分多个调度器
            instanceId: AUTO                # Quartz实例ID，AUTO表示自动生成唯一ID
          threadPool:
            threadCount: 5                  # 线程池中线程的数量，决定可以同时执行的任务数
            threadPriority: 5               # 线程优先级，范围1-10，默认是5
          jobStore:
            class: org.quartz.simple.RAMJobStore # 使用内存存储（默认），所有任务信息存储在内存中
            misfireThreshold: 5000          # 错失触发时间的阈值，单位毫秒，默认60000ms（1分钟）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启 sql 日志
    map-underscore-to-camel-case: true