server:
  port: 9090
  servlet:
    context-path: /admin
spring:
  application:
    name: deliver-admin
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB
