server:
  port: 7070
spring:
  application:
    name: deliver-server
  profiles:
    active: dev

# 对称加密
aes:
  key: oszero

message-link-trace:
  file:
    path: /logs/messageLinkTrace
    name: messageLinkTrace.log
