# MQ 类型选择
mq-type: rocketmq

rocketmq:
  # NameServer地址
  name-server: localhost:8080

spring:
  redis:
    port: 6379
    host: localhost
    password:
    database: 0
    timeout: 60s
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 0
        max-wait: 5s
  datasource:
    url: jdbc:mysql://localhost:3306/deliver?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # RabbitMQ 配置
  rabbitmq:
    virtual-host:
    host:
    port:
    username:
    password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启 sql 日志
    map-underscore-to-camel-case: true
